Repository poetapp/node, pull requests merged in 2018-12, with the labels that each got.

#838 feat(Health): inject ipfsHashTxId into Health module
  src/Health/ExchangeConfiguration.ts
  src/Health/Health.ts
  src/Messaging/ExchangeConfiguration.ts
  src/Messaging/Messages.ts
  src/Messaging/Messaging.ts
  src/app.ts
Labels: in progress

#843 Document some architecture in src/README
  src/README.md
Labels: in progress

#846 chore(Health): inject poetAnchorDownloaded to module
  src/Health/ExchangeConfiguration.ts
  src/Health/Health.ts
  src/app.ts
Labels: in progress

#836 refactor: StorageWriter factories and no DI framework
  src/README.md
  src/StorageWriter/ClaimController.ts
  src/StorageWriter/DAOClaims.ts
  src/StorageWriter/DAOIntegrityCheckFailures.ts
  src/StorageWriter/Router.ts
  src/StorageWriter/Service.ts
  src/StorageWriter/StorageWriter.ts
  src/app.ts
Labels: in progress

#856 refactor: Drop InversifyJS: BatchReader
  src/BatchReader/BatchReader.ts
  src/BatchReader/ClaimController.ts
  src/BatchReader/DirectoryDAO.ts
  src/BatchReader/IPFS.ts
  src/BatchReader/Router.ts
  src/BatchReader/Service.ts
Labels: in progress

#857 refactor: Drop InversifyJS: BatchWriter
  src/BatchWriter/BatchWriter.ts
  src/BatchWriter/ClaimController.ts
  src/BatchWriter/FileDAO.ts
  src/BatchWriter/IPFS.ts
  src/BatchWriter/Router.ts
  src/BatchWriter/Service.ts
Labels: in progress

#860 refactor: Drop InversifyJS: BlockchainReader
  src/BlockchainReader/BlockchainReader.ts
  src/BlockchainReader/Controller.ts
  src/BlockchainReader/DAO.ts
  src/BlockchainReader/Service.ts
Labels: in progress

#863 refactor: Drop InversifyJS: StorageReader
  src/StorageReader/ClaimController.ts
  src/StorageReader/IPFS.ts
  src/StorageReader/Router.ts
  src/StorageReader/Service.ts
  src/StorageReader/StorageReader.ts
Labels: in progress

#866 refactor: Drop InversifyJS: API
  src/API/API.ts
  src/API/FileController.ts
  src/API/FileDAO.ts
  src/API/HealthController.ts
  src/API/Router.ts
  src/API/WorkController.ts
Labels: in progress

#865 refactor: Drop InversifyJS: Health
  src/Health/Health.ts
  src/Health/HealthController.ts
  src/Health/HealthDAO.ts
  src/Health/HealthService.ts
  src/Health/IPFS.ts
  src/Health/IPFSDirectoryHashDAO.ts
  src/Health/Router.ts
Labels: in progress

#864 refactor: Drop InversifyJS: View
  src/View/Router.ts
  src/View/View.ts
  src/View/WorkController.ts
Labels: in progress

#870 refactor: uninstall inversify + remove last couple remnants
  package-lock.json
  package.json
  src/Health/Health.ts
  src/StorageWriter/StorageWriter.ts
Labels: in progress

#877 chore: Delete random code
  src/Health/HealthDAO.ts
Labels: in progress

#876 refactor: Fix namespacing of Service
  src/StorageWriter/Service.ts
  src/StorageWriter/StorageWriter.ts
Labels: in progress

#880 Add await in Messaging
  src/Messaging/Messaging.ts
Labels: in progress

#878 feat(Health): roll transactionAnchorRetryInfo into health collection
  src/Health/Health.ts
  src/Health/HealthController.ts
  src/Health/HealthDAO.ts
  src/Health/HealthService.ts
  src/Health/IPFSDirectoryHashDAO.ts
  src/Health/Router.ts
Labels: in progress

#873 chore(travis): set logging level to warn
  .travis.yml
  docker-compose.travis.yml
Labels: in progress

#362 Exceptions, Unit Test
  src/Exceptions.test.ts
  tests/unit/index.ts
Labels: in progress, quality

#888 fix typo
  src/Health/Health.ts
  src/Health/HealthController.ts
Labels: in progress

#889 chore(Health): consolidate interface
  src/Health/IPFSDirectoryHashDAO.ts
Labels: in progress

#890 refactor(BlockchainWriter): remove BlockInfoDAO
  src/BlockchainWriter/BlockInfoDAO.ts
  tests/integration/BlockchainWriter/BlockInfoDAO.test.ts
  tests/integration/index.ts
Labels: in progress

#867 test: Functional test, Fork Detected
  src/BlockchainReader/BlockchainReader.ts
  src/BlockchainReader/Controller.ts
  src/BlockchainReader/ExchangeConfiguration.ts
  src/Configuration.ts
  src/Messaging/ExchangeConfiguration.ts
  src/Messaging/Messages.ts
  src/Messaging/Messaging.ts
  src/app.ts
  tests/functional/fork_detected.ts
  tests/functional/index.ts
  tests/functional/transaction_timeout.ts
  tests/helpers/bitcoin.ts
  tests/helpers/rabbitMQ.ts
  tests/helpers/utils.ts
  tests/integration/API/GetWork.test.ts
  tests/integration/API/GetWorks.test.ts
  tests/integration/API/GetWorksByIssuer.test.ts
  tests/integration/API/PostFile.test.ts
  tests/integration/API/PostWork.test.ts
  tests/integration/SecurityHeaders.test.ts
Labels: in progress, testing

#342 test: Unit Test HttpExceptionsMiddleware
  src/API/Middlewares/HttpExceptionsMiddleware.test.ts
  src/API/Middlewares/HttpExceptionsMiddleware.ts
  tests/unit/index.ts
Labels: in progress, quality

#892 chore: delete ./queries
  queries/README.md
  queries/attempt-count.mongo
  queries/reset-storage.mongo
  queries/storage-errors.mongo
  queries/storage-invalid-json.mongo
Labels: in progress

#896 feat(Health): upsert number of attempts to anchor an IPFS directory hash
  src/Health/HealthController.ts
  src/Health/HealthDAO.ts
  src/Health/IPFSDirectoryHashDAO.ts
  src/Health/Router.ts
  src/Interfaces.ts
Labels: in progress

#901 feat(API): retrieve transactionAnchor info in health report
  src/API/API.ts
  src/API/HealthController.ts
  src/Health/HealthController.ts
  tests/functional/transaction_timeout.ts
Labels: in progress

#905 refactor: Factories Refactor: StorageReader: ClaimController
  src/StorageReader/ClaimController.ts
  src/StorageReader/StorageReader.ts
Labels: in progress

#911 refactor: Factories Refactor: StorageReader: Router
  src/StorageReader/Router.ts
  src/StorageReader/StorageReader.ts
Labels: in progress

#907 refactor: Factories Refactor: StorageReader: Service
  src/StorageReader/Service.ts
  src/StorageReader/StorageReader.ts
Labels: in progress

#915 refactor: Factories Refactor: StorageReader: IPFS
  src/StorageReader/IPFS.ts
  src/StorageReader/StorageReader.ts
Labels: in progress

#909 chore: Uninstall reflect-metadata
  package-lock.json
  package.json
  src/app.ts
Labels: in progress

#927 chore: address ipfs-api deprecation
  package-lock.json
  package.json
Labels: in progress

#919 fix(API): fix logger
  src/API/HealthController.ts
Labels: in progress

#923 refactor: Factories Refactor: View
  src/View/Router.ts
  src/View/View.ts
  src/View/WorkController.ts
  src/app.ts
Labels: in progress

#929 refactor(BlockchainWriter): able to run as independent module
  docker-compose.yml
  package.json
  src/BlockchainWriter/index.ts
  src/Helpers/moduleStartStopCatch.ts
  src/app.ts
Labels: don't merge, work in progress
