Repository poetapp/node, pull requests merged in 2018-10, with the labels that each got.

#487 Refactor RabbitMQ Config
  src/API/API.ts
  src/API/APIConfiguration.ts
  src/API/ExchangeConfiguration.ts
  src/API/Router.test.ts
  src/API/WorkController.test.ts
  src/API/WorkController.ts
  src/BatchReader/BatchReader.ts
  src/BatchReader/BatchReaderConfiguration.ts
  src/BatchReader/ExchangeConfiguration.ts
  src/BatchReader/Router.ts
  src/BatchReader/Service.ts
  src/BatchWriter/BatchWriter.ts
  src/BatchWriter/BatchWriterConfiguration.ts
  src/BatchWriter/ExchangeConfiguration.ts
  src/BatchWriter/Router.ts
  src/BatchWriter/Service.ts
  src/BlockchainReader/BlockchainReader.ts
  src/BlockchainReader/BlockchainReaderConfiguration.ts
  src/BlockchainReader/ExchangeConfiguration.ts
  src/BlockchainWriter/BlockchainWriter.ts
  src/BlockchainWriter/BlockchainWriterConfiguration.ts
  src/BlockchainWriter/Controller.ts
  src/BlockchainWriter/ExchangeConfiguration.ts
  src/BlockchainWriter/Router.ts
  src/Configuration.test.ts
  src/Configuration.ts
  src/Messaging/ExchangeConfiguration.ts
  src/Messaging/Messages.ts
  src/Messaging/Messaging.ts
  src/StorageReader/ClaimController.test.ts
  src/StorageReader/ExchangeConfiguration.ts
  src/StorageReader/Router.test.ts
  src/StorageReader/Router.ts
  src/StorageReader/Service.test.ts
  src/StorageReader/StorageReader.ts
  src/StorageReader/StorageReaderConfiguration.ts
  src/StorageWriter/ClaimController.test.ts
  src/StorageWriter/ClaimController.ts
  src/StorageWriter/ExchangeConfiguration.ts
  src/StorageWriter/Router.test.ts
  src/StorageWriter/Router.ts
  src/StorageWriter/StorageWriter.ts
  src/StorageWriter/StorageWriterConfiguration.ts
  src/View/ExchangeConfiguration.ts
  src/View/Router.test.ts
  src/View/Router.ts
  src/View/View.ts
  src/View/ViewConfiguration.ts
  src/app.ts
Labels: feature

#543 bug: exchange name not prefixed
  src/Configuration.test.ts
  src/Configuration.ts
Labels: bug

#559 Delete unit tests that are not true unit tests from View module
  src/View/Router.test.ts
  src/View/WorkController.test.ts
  tests/unit/index.ts
Labels: bug

#558 Delete unit tests that are not true unit tests from API module
  src/API/WorkController.test.ts
  tests/unit/index.ts
Labels: bug

#557 Delete unit tests that are not true unit tests from StorageReader module
  src/StorageReader/ClaimController.test.ts
  src/StorageReader/IPFS.test.ts
  src/StorageReader/Router.test.ts
  src/StorageReader/Service.test.ts
  tests/unit/index.ts
Labels: bug

#552 Move BatchReader Class Interfaces
  src/BatchReader/BatchReader.ts
  src/BatchReader/BatchReaderConfiguration.ts
  src/BatchReader/IPFS.ts
  src/BatchReader/IPFSConfiguration.ts
  src/BatchReader/Service.ts
  src/BatchReader/ServiceConfiguration.ts
Labels: refactor

#553 Move BatchWriter Class Interfaces
  src/BatchWriter/BatchWriter.ts
  src/BatchWriter/BatchWriterConfiguration.ts
  src/BatchWriter/IPFS.ts
  src/BatchWriter/IPFSConfiguration.ts
  src/BatchWriter/Service.ts
  src/BatchWriter/ServiceConfiguration.ts
Labels: refactor

#596 refactor: rewrite GetWorksByPublicKey tests using riteway
  test/Integration/GetWorksByPublicKey.ts
  tests/integration/API/GetWorksByPublicKey.test.ts
  tests/integration/index.ts
Labels: quality

#609 BREAKING CHANGE: Anchor optimization, ipfsDirectoryHash
  package-lock.json
  package.json
  src/BlockchainReader/Bitcoin.test.ts
  src/BlockchainReader/Bitcoin.ts
  src/BlockchainReader/TestData/block-000000000000f29b1e2d33590208811f3cd2b2c190596424617a18460d878288.json
  src/BlockchainReader/TestData/block-0000000070746b06bbec07a7cd35e0c6d47bfa4e2544a6a1d2aa6efc49d47679.json
  src/BlockchainWriter/Bitcoin.test.ts
  src/BlockchainWriter/Bitcoin.ts
  typings/bs58.d.ts
Labels: feature
