Repository poetapp/node, pull requests merged in 2018-05, with the labels that each got.

#85 Adds CODEOWNERS
  .github/CODEOWNERS
Labels: in progress

#82 Fix typo in README
  README.md
Labels: docs, in progress

#87 fixes lint failures
  .travis.yml
  package-lock.json
  package.json
  src/API/API.ts
  src/API/APIConfiguration.ts
  src/API/HttpExceptionsMiddleware.ts
  src/API/LoggerMiddleware.ts
  src/API/Router.ts
  src/API/WorkController.ts
  src/BlockchainReader/BlockchainReader.ts
  src/BlockchainReader/BlockchainReaderConfiguration.ts
  src/BlockchainReader/BlockchainReaderService.ts
  src/BlockchainReader/ClaimController.ts
  src/BlockchainReader/ClaimControllerConfiguration.ts
  src/BlockchainWriter/BlockchainWriter.ts
  src/BlockchainWriter/BlockchainWriterConfiguration.ts
  src/BlockchainWriter/ClaimController.ts
  src/BlockchainWriter/ClaimControllerConfiguration.ts
  src/BlockchainWriter/Router.ts
  src/BlockchainWriter/Service.ts
  src/Configuration.ts
  src/Error.ts
  src/Helpers/Logging.ts
  src/Messaging/Messages.ts
  src/Messaging/Messaging.ts
  src/Storage/ClaimController.ts
  src/Storage/IPFS.ts
  src/Storage/IPFSConfiguration.ts
  src/Storage/Router.ts
  src/Storage/Service.ts
  src/Storage/Storage.ts
  src/Storage/StorageConfiguration.ts
  src/View/Router.ts
  src/View/WorkController.ts
  src/index.ts
  test/Claims.ts
  test/Integration/GetWork.ts
  test/Integration/GetWorksByPublicKey.ts
  test/Integration/Helper.ts
  test/Integration/PostWork.ts
  test/Keys.ts
  test/PrepareDB.ts
  test/Script.ts
Labels: in progress

#99 @po.et/tslint-rules@1.2.0
  package-lock.json
  package.json
  src/API/API.ts
  src/API/HttpExceptionsMiddleware.ts
  src/API/LoggerMiddleware.ts
  src/API/Router.ts
  src/API/WorkController.ts
  src/BlockchainReader/BlockchainReader.ts
  src/BlockchainReader/BlockchainReaderService.ts
  src/BlockchainReader/ClaimController.ts
  src/BlockchainWriter/BlockchainWriter.ts
  src/BlockchainWriter/ClaimController.ts
  src/BlockchainWriter/Router.ts
  src/BlockchainWriter/Service.ts
  src/Configuration.ts
  src/Error.ts
  src/Helpers/Logging.ts
  src/Messaging/Messages.ts
  src/Messaging/Messaging.ts
  src/Storage/ClaimController.ts
  src/Storage/IPFS.ts
  src/Storage/Router.ts
  src/Storage/Service.ts
  src/Storage/Storage.ts
  src/Storage/StorageConfiguration.ts
  src/View/Router.ts
  src/View/WorkController.ts
  src/index.ts
  test/Claims.ts
  test/Integration/GetWork.ts
  test/Integration/GetWorksByPublicKey.ts
  test/Integration/Helper.ts
  test/Integration/PostWork.ts
  test/Keys.ts
  test/PrepareDB.ts
  test/Script.ts
Labels: quality

#107 Docker build tag
  .travis.yml
  makefile
Labels: architecture, bug, infrastructure
