Repository poetapp/node, pull requests merged in 2018-11, with the labels that each got.

#659 feat: Refactor version anchor
  package-lock.json
  package.json
  src/BlockchainReader/Bitcoin.test.ts
  src/BlockchainReader/Bitcoin.ts
  src/BlockchainReader/Controller.ts
  src/BlockchainWriter/Bitcoin.test.ts
  src/BlockchainWriter/Bitcoin.ts
  src/BlockchainWriter/Controller.ts
  src/Configuration.ts
  src/Messaging/Messages.test.ts
  src/Messaging/Messages.ts
Labels: refactor

#754 test: K6 Stress Testing Tool
  Docker/Dockerfile.stress
  docker-compose.yml
  package.json
  tests/stress/README.md
  tests/stress/createClaimAPI.ts
  tests/stress/createWorks.js
  tests/stress/getWork.js
  tests/stress/getWorks.js
Labels: testing

#777 feat: update BlockchainWriter DAO on blockDownloaded event
  src/BlockchainWriter/Controller.test.ts
  src/BlockchainWriter/Controller.ts
  src/BlockchainWriter/DAO.ts
  src/BlockchainWriter/Router.ts
  tests/unit/index.ts
Labels: don't merge, work in progress

#803 test: Improve Stress Code Create Work
  package-lock.json
  package.json
  tests/stress/createClaimAPI.ts
  tests/stress/createWorks.js
Labels: testing

#833 chore: remove attempts from blockchainWriterDao
  src/BlockchainWriter/DAO.ts
Labels: in progress

#834 832 create dao for tracking ipfs directory hashes
  src/Health/Health.ts
  src/Health/IPFSDirectoryHashDAO.ts
Labels: in progress
