Repository poetapp/node, pull requests merged in 2018-09, with the labels that each got.

#347 Use await for creating claims
  .travis.yml
  README.md
  package-lock.json
  package.json
  src/API/Router.ts
  src/Helpers/Claim.ts
  src/Interfaces.test.ts
  src/Storage/ClaimController.ts
  src/StorageWriter/Router.ts
  test/Claims.ts
  test/Integration/GetWorks.ts
  test/Integration/GetWorksByPublicKey.ts
  test/Integration/Helper.ts
  test/Integration/PostWork.ts
  test/Script.ts
Labels: in progress

#451 fix(docker): inlcude gcc -5 and g++ -5 and refactor ci
  .dockerignore
  .travis.yml
  Dockerfile
  package-lock.json
  package.json
  scripts/docker-build.sh
  scripts/docker-push.sh
Labels: infrastructure, refactor, team-devops

#474 Refactor data output to poet anchor
  src/BlockchainReader/Bitcoin.test.ts
  src/BlockchainReader/Bitcoin.ts
Labels: don't merge

#480 Config rabbitmq
  package-lock.json
  src/Configuration.test.ts
  src/Configuration.ts
  src/Messaging/Messages.ts
  src/Messaging/Messaging.ts
Labels: don't merge, feature, work in progress
